module.exports = {
  REQUISITION_STATUS: {
    APPROVAL_PENDING: "APPROVAL_PENDING",
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    IN_PROCESS: "IN_PROCESS",
    //
    ORDER_PLACED: "ORDER_PLACED",
    //
    DELIVERED: "DELIVERED",
    PARTIALLY_DELIVERED: "PARTIALLY_DELIVERED",
  },
  ITEM_CATEGORIES: {
    SPECIAL_APPROVAL: "SPECIAL_APPROVAL",
    NORMAL: "NORMAL",
  },
  PAY_STATUS: {
    PAID: "PAID",
    NOT_PAID: "NOT_PAID",
  },
  PRIORITY: {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
  },
  clientTypes: {
    MANAGER: 'MANAGER',
    STAFF_MEMBER: 'STAFF_MEMBER',
    SITE_MANAGER: 'SITE_MANAGER',
  }
};
